from sqlalchemy import inspect, text

from .usernames import slug_nome_usuario


COLUNAS_BEBIDA = {
    "volume_ml": "INTEGER",
    "classificacao": "VARCHAR(100)",
    "madeira": "VARCHAR(100)",
    "tempo_envelhecimento_meses": "INTEGER",
    "cidade_origem": "VARCHAR(100)",
    "estado_origem": "VARCHAR(2)",
    "regiao_origem": "VARCHAR(100)",
    "alambique": "VARCHAR(150)",
    "produtor": "VARCHAR(150)",
    "lote": "VARCHAR(80)",
    "nutri_score": "VARCHAR(10)",
    "nova_grupo": "INTEGER",
    "eco_score": "VARCHAR(30)",
    "alergenos": "TEXT",
    "categorias": "TEXT",
    "quantidade": "VARCHAR(80)",
    "embalagem": "TEXT",
    "paises": "TEXT",
    "id_criado_por": "INTEGER",
}

COLUNAS_USUARIO = {
    "tipo_usuario": "VARCHAR(20) NOT NULL DEFAULT 'comum'",
    "nome_usuario": "VARCHAR(80)",
    "privacidade_versao_aceita": "VARCHAR(20)",
    "termos_versao_aceita": "VARCHAR(20)",
    "lgpd_aceite_em": "TIMESTAMP",
    "marketing_consentimento": "BOOLEAN DEFAULT FALSE",
    "marketing_consentimento_em": "TIMESTAMP",
    "anonimizado_em": "TIMESTAMP",
}


def aplicar_migracoes_leves(engine) -> None:
    inspector = inspect(engine)
    if "bebida" not in inspector.get_table_names():
        return

    colunas_bebida_existentes = {
        coluna["name"] for coluna in inspector.get_columns("bebida")
    }
    colunas_usuario_existentes = (
        {coluna["name"] for coluna in inspector.get_columns("usuario")}
        if "usuario" in inspector.get_table_names()
        else set()
    )

    with engine.begin() as connection:
        for nome, tipo_sql in COLUNAS_USUARIO.items():
            if nome not in colunas_usuario_existentes:
                connection.execute(
                    text(f"ALTER TABLE usuario ADD COLUMN {nome} {tipo_sql}")
                )

        if "usuario" in inspector.get_table_names():
            usuarios_sem_nome = connection.execute(
                text(
                    """
                    SELECT id_usuario, nome, email
                    FROM usuario
                    WHERE nome_usuario IS NULL OR nome_usuario = ''
                    ORDER BY id_usuario
                    """
                )
            ).mappings()
            usados = {
                row["nome_usuario"]
                for row in connection.execute(
                    text("SELECT nome_usuario FROM usuario WHERE nome_usuario IS NOT NULL AND nome_usuario <> ''")
                ).mappings()
            }
            for usuario in usuarios_sem_nome:
                base = slug_nome_usuario(
                    (usuario["email"] or "").split("@", 1)[0]
                    or usuario["nome"]
                    or f"usuario{usuario['id_usuario']}"
                )
                candidato = base
                sufixo = 1
                while candidato in usados:
                    sufixo += 1
                    limite = 80 - len(str(sufixo)) - 1
                    candidato = f"{base[:limite]}.{sufixo}"
                usados.add(candidato)
                connection.execute(
                    text("UPDATE usuario SET nome_usuario = :nome_usuario WHERE id_usuario = :id_usuario"),
                    {"nome_usuario": candidato, "id_usuario": usuario["id_usuario"]},
                )

            if engine.dialect.name == "sqlite":
                connection.execute(
                    text("CREATE UNIQUE INDEX IF NOT EXISTS ix_usuario_nome_usuario ON usuario (nome_usuario)")
                )
            else:
                connection.execute(
                    text("CREATE UNIQUE INDEX IF NOT EXISTS ix_usuario_nome_usuario ON usuario (nome_usuario)")
                )

        if engine.dialect.name != "sqlite":
            for tabela in ("avaliacao", "preco"):
                if tabela in inspector.get_table_names():
                    connection.execute(text(f"ALTER TABLE {tabela} ALTER COLUMN id_usuario DROP NOT NULL"))
            if "eco_score" in colunas_bebida_existentes:
                connection.execute(text("ALTER TABLE bebida ALTER COLUMN eco_score TYPE VARCHAR(30)"))

        for nome, tipo_sql in COLUNAS_BEBIDA.items():
            if nome not in colunas_bebida_existentes:
                connection.execute(
                    text(f"ALTER TABLE bebida ADD COLUMN {nome} {tipo_sql}")
                )

        if "cachaca" not in inspector.get_table_names():
            id_sql = (
                "INTEGER PRIMARY KEY AUTOINCREMENT"
                if engine.dialect.name == "sqlite"
                else "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"
            )
            connection.execute(
                text(
                    f"""
                    CREATE TABLE cachaca (
                        id_cachaca {id_sql},
                        id_bebida INTEGER NOT NULL UNIQUE REFERENCES bebida(id_bebida),
                        volume_ml INTEGER,
                        classificacao VARCHAR(100),
                        madeira VARCHAR(100),
                        tempo_envelhecimento_meses INTEGER,
                        cidade_origem VARCHAR(100),
                        estado_origem VARCHAR(2),
                        regiao_origem VARCHAR(100),
                        alambique VARCHAR(150),
                        produtor VARCHAR(150),
                        lote VARCHAR(80),
                        criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )

        if "password_reset_token" not in inspector.get_table_names():
            id_sql = (
                "INTEGER PRIMARY KEY AUTOINCREMENT"
                if engine.dialect.name == "sqlite"
                else "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"
            )
            connection.execute(
                text(
                    f"""
                    CREATE TABLE password_reset_token (
                        id_reset {id_sql},
                        id_usuario INTEGER NOT NULL REFERENCES usuario(id_usuario),
                        token_hash VARCHAR(64) NOT NULL UNIQUE,
                        expiracao TIMESTAMP NOT NULL,
                        usado BOOLEAN NOT NULL DEFAULT FALSE,
                        usado_em TIMESTAMP,
                        criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            connection.execute(
                text(
                    "CREATE INDEX ix_password_reset_token_token_hash "
                    "ON password_reset_token (token_hash)"
                )
            )

        connection.execute(
            text(
                """
                INSERT INTO cachaca (
                    id_bebida,
                    volume_ml,
                    classificacao,
                    madeira,
                    tempo_envelhecimento_meses,
                    cidade_origem,
                    estado_origem,
                    regiao_origem,
                    alambique,
                    produtor,
                    lote
                )
                SELECT
                    b.id_bebida,
                    b.volume_ml,
                    b.classificacao,
                    b.madeira,
                    b.tempo_envelhecimento_meses,
                    b.cidade_origem,
                    b.estado_origem,
                    b.regiao_origem,
                    b.alambique,
                    b.produtor,
                    b.lote
                FROM bebida b
                WHERE lower(coalesce(b.tipo, '')) LIKE '%cach%'
                  AND NOT EXISTS (
                    SELECT 1 FROM cachaca c WHERE c.id_bebida = b.id_bebida
                  )
                  AND (
                    b.volume_ml IS NOT NULL
                    OR b.classificacao IS NOT NULL
                    OR b.madeira IS NOT NULL
                    OR b.tempo_envelhecimento_meses IS NOT NULL
                    OR b.cidade_origem IS NOT NULL
                    OR b.estado_origem IS NOT NULL
                    OR b.regiao_origem IS NOT NULL
                    OR b.alambique IS NOT NULL
                    OR b.produtor IS NOT NULL
                    OR b.lote IS NOT NULL
                  )
                """
            )
        )

        connection.execute(
            text(
                """
                DELETE FROM cachaca
                WHERE id_bebida IN (
                    SELECT id_bebida
                    FROM bebida
                    WHERE lower(coalesce(tipo, '')) NOT LIKE '%cach%'
                      AND lower(coalesce(tipo, '')) NOT LIKE '%aguardente%'
                )
                """
            )
        )
